#Minecraft server properties
#Fri Dec 12 19:00:51 EST 2025
level-name=world
hellworld=false
spawn-monsters=true
online-mode=false
spawn-animals=true
max-players=20
server-ip=
pvp=true
server-port=25565
